#=============================================================================
# Test requests
#=============================================================================

# Replace the <your-api-management-service-name> and <your-function-app-name> with your actual API Management service name and Function App hostname
@apimHostname = <your-api-management-service-name>.azure-api.net
@functionAppHostname = <your-function-app-name>.azurewebsites.net

# Replace <your-call-protected-api-workflow-url> with your actual URL of the 'call-protected-api-workflow' workflow
@callProtectedApiWorkflowUrl = <your-call-protected-api-workflow-url>


#=============================================================================
# Test requests for the Unprotected API on API Management
#=============================================================================

# Call GET on Unprotected API
GET https://{{apimHostname}}/unprotected HTTP/1.1

###

# Call POST on Unprotected API
POST https://{{apimHostname}}/unprotected HTTP/1.1

###

# Call DELETE on Unprotected API (should return 401 Unauthorized because managed identity does not have the Sample.Delete permission)
DELETE https://{{apimHostname}}/unprotected HTTP/1.1

###


#=============================================================================
# Test requests for the Azure Function
#=============================================================================

# Call GET on Azure Function
GET https://{{functionAppHostname}}/api/CallProtectedApiFunction HTTP/1.1

###

# Call POST on Azure Function
POST https://{{functionAppHostname}}/api/CallProtectedApiFunction HTTP/1.1

###

# Call DELETE on Azure Function
DELETE https://{{functionAppHostname}}/api/CallProtectedApiFunction HTTP/1.1

###


#=============================================================================
# Test requests for the Logic App workflow
#=============================================================================

# Trigger workflow that will call GET the protected API
POST {{callProtectedApiWorkflowUrl}} HTTP/1.1
Content-Type: application/json

{
    "httpMethod": "GET"
}

###

# Trigger workflow that will call POST the protected API
POST {{callProtectedApiWorkflowUrl}} HTTP/1.1
Content-Type: application/json

{
    "httpMethod": "POST"
}

###

# Trigger workflow that will call DELETE the protected API (should return 401 Unauthorized because managed identity does not have the Sample.Delete permission)
POST {{callProtectedApiWorkflowUrl}} HTTP/1.1
Content-Type: application/json

{
    "httpMethod": "DELETE"
}